# Generated by Django 5.2.14 on 2026-06-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField()),
                ('image_url', models.URLField(blank=True)),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='RSSSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('category_hint', models.CharField(choices=[('asosiy', 'Asosiy'), ('texnologiya', 'Texnologiya'), ('talim', 'Talim'), ('sport', 'Sport'), ('jahon', 'Jahon')], default='asosiy', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
